workflows:
  android-receiver-release:
    name: Android Receiver - Release Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    
    environment:
      # Flutter Version
      flutter: stable
      
      # Environment Variables dari Codemagic
      # Set ini di Codemagic UI: App Settings > Environment Variables
      vars:
        # SUPABASE_URL: "https://your-project.supabase.co"
        # SUPABASE_ANON_KEY: "your_anon_key_here"
        
        # Optional: Build configuration
        JAVA_HOME: /Library/Java/JavaVirtualMachines/zulu-17.jdk/Contents/Home
      
      groups:
        # Jika menggunakan group untuk credentials
        - supabase_credentials
    
    scripts:
      - name: Build release APK
        script: |
          set -e # Exit on error
          set -x # Print commands
          
          echo "Current directory: $(pwd)"
          ls -la
          
          # Handle directory structure (if running from root)
          if [ ! -f "pubspec.yaml" ] && [ -d "android_receiver" ]; then
            echo "Changing directory to android_receiver"
            cd android_receiver
          fi
          
          echo "Checking dependencies..."
          flutter pub get
          
          echo "Building APK..."
          flutter clean
          flutter build apk --release
          
          echo "Build finished. Collecting artifacts..."
          mkdir -p ../build_artifacts
          find build -name "*.apk" -exec cp {} ../build_artifacts/ \;
          
          echo "Artifacts collected:"
          ls -la ../build_artifacts
          
    artifacts:
      - build_artifacts/*.apk
    
    publishing:
      # Email notification
      email:
        recipients:
          - your-email@example.com
        notify:
          success: true
          failure: true
      
      # Optional: Auto-publish ke Google Play (uncomment jika perlu)
      # google_play:
      #   credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
      #   track: internal
      #   submit_as_draft: true
